apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedicated-essentials-deployment
  labels:
    app: dedicated-essentials
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dedicated-essentials
  template:
    metadata:
      labels:
        app: dedicated-essentials
    spec:
      containers:
      - name: dedicated-essentials
        image: shedi/wowaudit:latest
        command: ["/srv/bin/refresh"]
        args: ["dedicated-essentials"]

        resources:
          requests:
            cpu: 250m
            memory: 200Mi

          limits:
            cpu: 250m
            memory: 400Mi

      imagePullSecrets:
        - name: regcred
