apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedicated-blizzard-deployment
  labels:
    app: dedicated-blizzard
spec:
  replicas: 6
  selector:
    matchLabels:
      app: dedicated-blizzard
  template:
    metadata:
      labels:
        app: dedicated-blizzard
    spec:
      containers:
      - name: dedicated-blizzard
        image: shedi/wowaudit:latest
        command: ["/srv/bin/refresh"]
        args: ["dedicated-blizzard"]

        resources:
          requests:
            cpu: 250m
            memory: 350Mi

          limits:
            cpu: 250m
            memory: 600Mi

      imagePullSecrets:
        - name: regcred
